#cloud-config
package_update: true
packages:
  - apache2

write_files:
  - path: /var/www/html/index.html
    owner: root:root
    permissions: "0644"
    defer: true
    content: "<h1>Multiterra</h1>"

runcmd:
  - systemctl enable apache2
  - systemctl restart apache2
